# Generated by Django 4.2.7 on 2026-06-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionFinales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Directivo', 'Director'), ('Secretario', 'Secretario'), ('Preceptor', 'Preceptor'), ('Profesor', 'Profesor'), ('Estudiante', 'Estudiante')], default='Estudiante', max_length=20),
        ),
    ]
