# Generated by Django 4.2.7 on 2026-07-01 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionFinales', '0002_alter_usuario_is_superuser_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255, verbose_name='Acción')),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.CharField(blank=True, max_length=100, verbose_name='ID del objeto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
