# Generated by Django 4.2.7 on 2026-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionFinales', '0003_registroauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre_materia',
            field=models.CharField(max_length=200, verbose_name='nombre_materia'),
        ),
    ]
