# Generated by Django 4.2.7 on 2026-09-17 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionFinales', '0004_alter_materia_nombre_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos (código de área + número, sin espacios ni guiones). Ej: 2211234567')], verbose_name='telefono_1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos (código de área + número, sin espacios ni guiones). Ej: 2211234567')], verbose_name='telefono_2'),
        ),
    ]
