# Generated by Django 4.2.7 on 2026-09-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionFinales', '0006_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Directivo', 'Director/a'), ('Secretario', 'Secretario/a'), ('Preceptor', 'Preceptor/a'), ('Profesor', 'Profesor/a'), ('Estudiante', 'Estudiante')], default='Estudiante', max_length=20),
        ),
    ]
