# Generated by Django 4.2.7 on 2026-09-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscripcionFinales", "0007_alter_usuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instituto",
            name="telefono_1",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="telefono_1"
            ),
        ),
        migrations.AlterField(
            model_name="instituto",
            name="telefono_2",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="telefono_2"
            ),
        ),
    ]
