# Generated by Django 4.2.7 on 2026-10-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionFinales', '0008_alter_instituto_telefono_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios_materia',
            name='estado',
            field=models.CharField(choices=[('EN_CURSO', 'En curso'), ('REGULAR', 'Cursada aprobada / Habilitado a final'), ('PROMOCIONADO', 'Promocionado'), ('APROBADO', 'Final aprobado'), ('RECURSA', 'Recursa'), ('ABANDONO', 'Abandono')], default='EN_CURSO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='usuarios_materia',
            name='fecha_regularidad',
            field=models.DateField(blank=True, help_text='Fecha en que se aprobó la cursada. Reservado para cuando se active el vencimiento de regularidad.', null=True, verbose_name='Fecha de regularidad'),
        ),
    ]
