# Generated by Django 4.2.7 on 2026-10-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionFinales', '0011_normalizar_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_materia',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('Oyente', 'Oyente'), ('Regular', 'Regular'), ('Libre', 'Libre'), ('Itinerante', 'Itinerante')], max_length=20, null=True, verbose_name='Modalidad'),
        ),
    ]
