# Generated by Django 4.2.7 on 2026-10-04 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionFinales', '0012_alter_usuarios_materia_modalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TribunalMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Presidente', 'Presidente'), ('Vocal', 'Vocal')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribunales', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribunal', to='inscripcionFinales.mesafinal')),
                ('reemplaza_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazado_por', to='inscripcionFinales.tribunalmesa')),
            ],
            options={
                'verbose_name': 'Tribunal de mesa',
                'verbose_name_plural': 'Tribunales de mesa',
                'ordering': ['mesa_id', 'rol', 'fecha_asignacion'],
            },
        ),
    ]
