# Generated by Django 4.2.7 on 2026-10-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inscripcionFinales", "0004_alter_usuario_telefonos"),
        ("inscripcionFinales", "0013_tribunalmesa"),
    ]

    operations = []
